channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    ## Base packages.
    - black
    - tqdm
    - fire
    - jupyterlab
    - ipywidgets
    - seaborn
    - palettable
    - pandas
    - wandb
    - numpy
    - scipy
    - scikit-learn